blueprint: Add support for blueprint fabric-addressing-policy API
Apstra/apstra-api-python pull request #41
Opened 2022-10-31 08:57 UTC by shun159

Add support for blueprint fabric-addressing-policy API. 
For the details for the API, please refer to `/api/blueprints/{blueprint_id}/fabric-addressing-policy` on Apstra REST API Explorer.

2022-10-31 08:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Apstra/apstra-api-python?pullRequest=41) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Apstra/apstra-api-python?pullRequest=41) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Apstra/apstra-api-python?pullRequest=41) it.</sub>

2022-10-31 13:08 UTC, that1guy15 commented
Thanks for the contribution. 
Please add test coverage to tests/test_blueprint.py for all new logic.

2022-10-31 16:20 UTC, shun159 commented
@that1guy15 
Hi! Thank you for your review. I have added unit test cases for the new functions.

2022-11-04 18:33 UTC, that1guy15 commented
please address failed[ liniting and tests](https://github.com/Apstra/apstra-api-python/actions/runs/3362906297/jobs/5647016204). Also make sure to update version number in [setup ](https://github.com/Apstra/apstra-api-python/blob/main/setup.py#L12)

2022-11-04 18:34 UTC, that1guy15 requested changes
Linting and tests fail in actions. 
version number needs to be updated.

2022-11-08 03:43 UTC, shun159 commented
Hi I have fixed for the request.

2022-11-10 15:31 UTC, that1guy15 approved these changes
LGTM

2022-11-10 15:32 UTC, merged