blueprint: Add support for GET /api/blueprints/{bp_id}/relationships
Apstra/apstra-api-python pull request #44
Opened 2022-11-10 18:13 UTC by shun159

Add support for GET `/api/blueprints/{bp_id}/relationships`
This API is useful in some use cases like finding a pair of interface and device.

2022-12-06 17:00 UTC, that1guy15 requested changes
One comment and you need to rebase and bump version #. 
Looks good, thank you!

2022-12-23 03:12 UTC, shun159 commented on aos/blueprint.py
> +            url += f'?{query_str}'
@that1guy15 

Thank you for your review!
Please tell me how I can put queries in header? (I don't know how to do except for append into URL)

2022-12-23 04:39 UTC, that1guy15 commented on aos/blueprint.py
> +            url += f'?{query_str}'
If you look at the `[json_resp_get()](https://github.com/Apstra/apstra-api-python/blob/main/aos/aos.py#L223)` method you will see it takes `params` as an optional argument as a dictionary with your query parameters as key/value pairs. This library is designed to take params and pass them in through the headers when populated so you dont have to work with them raw in the `url`

There are examples through out this library that are using the `params` argument in the rest class. Here is a good example: https://github.com/Apstra/apstra-api-python/blob/main/aos/blueprint.py#L536

2022-12-23 05:54 UTC, shun159 commented on aos/blueprint.py
> +            url += f'?{query_str}'
Good advice! I have fixed to use params instead of querystring. How about that?

2022-12-23 05:55 UTC, shun159 commented on aos/blueprint.py
> +            url += f'?{query_str}'
And rebased to bump version number.

2022-12-23 15:27 UTC, that1guy15 approved these changes

2022-12-23 15:28 UTC, that1guy15 approved these changes
LGTM

2022-12-23 15:28 UTC, merged